# version: "3"

# services:
#   nginx:
#     image: nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - web1
#       - web2

#   web1:
#     image: your-docker-server-image1
#     ports:
#       - "5000:5000"

#   web2:
#     image: your-docker-server-image2
#     ports:
#       - "5001:5000"

version: '3'

networks:
  my-network:
    driver: bridge

services:
  backend:
    image: ta-backend
    networks:
      - my-network

  frontend:
    image: ta-frontend
    networks:
      - my-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network