version: '3'

networks:
  my-network:
    driver: bridge

services:
  backend:
    image: ta-backend
    networks:
      - my-network

  frontend:
    image: ta-frontend
    networks:
      - my-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network